const { EmbedBuilder } = require('discord.js');

const { SlashCommandBuilder } = require('@discordjs/builders');

module.exports = {
    data: new SlashCommandBuilder()
		.setName('contact')
		.setDescription('Get someone\'s contact information')
        .addStringOption(option =>
            option.setName('name')
                .setDescription('name')
                .addChoices({name: 'Aidan', value: 'aidan'},{name: 'Andy', value: 'andy'},{name: 'Ashley', value: 'ashley'},{name: 'Felix', value: 'felix'},{name: 'Da', value: 'da'},{name: 'Nick', value: 'nick'},{name: 'Michael', value: 'michael'},{name: 'Pob', value: 'pob'},{name: 'Sofie', value: 'sofie'},{name: 'Toby', value: 'toby'},)
                .setRequired(true)),    
    async execute(interaction) {
        const name = interaction.options.getString('name')
        aidanContact = new EmbedBuilder().setColor('#d0753c').setTitle("Aidan").setDescription('Contact Info').setThumbnail('https://cdn.discordapp.com/emojis/752953671897186304.webp?size=240&quality=lossless').addFields({ name: 'Phone Number', value: '919-830-1753'},{ name: 'Discord', value: 'Father_Cheddar#6969'},{ name: 'Email', value: 'gillaspyaidan@gmail.com'},{ name: 'Battle.net', value: 'PapaCheese#11594'},{ name: 'Steam', value: 'Father_Cheddar'}).setTimestamp().setFooter({ text: 'Brought to you by YTPT Bot', iconURL: 'https://cdn.discordapp.com/emojis/810653717690318918.webp?size=240&quality=lossless' });
        andyContact = new EmbedBuilder().setColor('#5acafa').setTitle("Andy").setDescription('Contact Info').setThumbnail('https://cdn.discordapp.com/emojis/759289782026108938.webp?size=240&quality=lossless').addFields( { name: 'Phone Number', value: '202-746-9323'}, { name: 'Discord', value: 'Zeta#6969'}, { name: 'Email', value: 'mastercrafter171@gmail.com'}, { name: 'Battle.net', value: 'Zeta#12138'}, { name: 'Steam', value: 'Zeta'} ).setTimestamp() .setFooter({ text: 'Brought to you by YTPT Bot', iconURL: 'https://cdn.discordapp.com/emojis/810653717690318918.webp?size=240&quality=lossless' });
        ashleyContact = new EmbedBuilder() .setColor('#8c5cca') .setTitle("Ashley") .setDescription('Contact Info') .setThumbnail('https://cdn.discordapp.com/emojis/731090114784264203.webp?size=240&quality=lossless') .addFields( { name: 'Phone Number', value: '571-471-0500'}, { name: 'Discord', value: 'ghostlywords#0216'}, { name: 'Email', value: 'idfk'}, { name: 'Steam', value: 'Ghostly Words'} ) .setTimestamp() .setFooter({ text: 'Brought to you by YTPT Bot', iconURL: 'https://cdn.discordapp.com/emojis/810653717690318918.webp?size=240&quality=lossless' });
        felixContact = new EmbedBuilder() .setColor('#4900f2') .setTitle("Claire") .setDescription('Contact Info') .setThumbnail('https://cdn.discordapp.com/emojis/731090114784264203.webp?size=240&quality=lossless') .addFields( { name: 'Phone Number', value: '571-395-5324'}, { name: 'Discord', value: 'hello there#8225'}, { name: 'Email', value: 'idfk'}, { name: 'Steam', value: 'idfk, again'}, ) .setTimestamp() .setFooter({ text: 'Brought to you by YTPT Bot', iconURL: 'https://cdn.discordapp.com/emojis/810653717690318918.webp?size=240&quality=lossless' });
        daContact = new EmbedBuilder().setColor('#f2bdcf').setTitle("Da")    .setDescription('Contact Info').setThumbnail('https://cdn.discordapp.com/emojis/755796906382327848.webp?size=240&quality=lossless').addFields({ name: 'Phone Number', value: '703-795-3533'},{ name: 'Discord', value: 'twivight#6690'}, { name: 'Email', value: 'danielfried05@gmail.com'}, { name: 'Battle.net', value: 'DFKronos#1333'}, { name: 'Steam', value: 'dfkronos'}, ) .setTimestamp() .setFooter({ text: 'Brought to you by YTPT Bot', iconURL: 'https://cdn.discordapp.com/emojis/810653717690318918.webp?size=240&quality=lossless' });
        nickContact = new EmbedBuilder() .setColor('#ffffff') .setTitle("Nick") .setDescription('Contact Info') .setThumbnail('https://cdn.discordapp.com/emojis/944738433916608603.webp?size=240&quality=lossless') .addFields( { name: 'Phone Number', value: '571-425-6609'}, { name: 'Discord', value: 'Advance#4368'}, { name: 'Email', value: 'nicholas.a.huber@gmail.com'}, { name: 'Battle.net', value: 'Advance#11101'}, { name: 'Steam', value: 'Advance'}, ) .setTimestamp() .setFooter({ text: 'Brought to you by YTPT Bot', iconURL: 'https://cdn.discordapp.com/emojis/810653717690318918.webp?size=240&quality=lossless' });
        michaelContact = new EmbedBuilder() .setColor('#bd194d') .setTitle("Michael") .setDescription('Contact Info') .setThumbnail('https://cdn.discordapp.com/emojis/836404047133147157.webp?size=240&quality=lossless') .addFields( { name: 'Phone Number', value: '571-337-0894'}, { name: 'Discord', value: 'DemolitionDonut#7650'}, { name: 'Email', value: 'mycutekittyface@gmail.com'}, { name: 'Battle.net', value: 'DemoDonut#1878'}, { name: 'Steam', value: 'Squeaky_Puffin'}, ) .setTimestamp() .setFooter({ text: 'Brought to you by YTPT Bot', iconURL: 'https://cdn.discordapp.com/emojis/810653717690318918.webp?size=240&quality=lossless' });
        sofieContact = new EmbedBuilder() .setColor('#53aa80') .setTitle("Sofie") .setDescription('Contact Info') .setThumbnail('https://cdn.discordapp.com/emojis/752952940049989694.webp?size=240&quality=lossless') .addFields( { name: 'Phone Number', value: '703-598-6032'}, { name: 'Discord', value: 'iSleepy#4602'}, { name: 'Email', value: 'idfk'}, { name: 'Battle.net', value: 'iSleepy#11585'}, { name: 'Steam', value: 'Yellow_Stars'}, ) .setTimestamp() .setFooter({ text: 'Brought to you by YTPT Bot', iconURL: 'https://cdn.discordapp.com/emojis/810653717690318918.webp?size=240&quality=lossless' });
        pobContact = new EmbedBuilder() .setColor('#ead16b') .setTitle("Pob") .setDescription('Contact Info') .setThumbnail('https://cdn.discordapp.com/emojis/752952822370271343.webp?size=240&quality=lossless') .addFields( { name: 'Phone Number', value: '571-326-7644'}, { name: 'Discord', value: 'pobhee#1348'}, { name: 'Email', value: 'phoebedawg123@gmail.com'}, { name: 'Battle.net', value: 'pobhee#1928'}, { name: 'Steam', value: 'Pobhee'}, ) .setTimestamp() .setFooter({ text: 'Brought to you by YTPT Bot', iconURL: 'https://cdn.discordapp.com/emojis/810653717690318918.webp?size=240&quality=lossless' });
        tobyContact = new EmbedBuilder() .setColor('#df1b1e') .setTitle("Toby") .setDescription('Contact Info') .setThumbnail('https://cdn.discordapp.com/emojis/896622971500757033.webp?size=240&quality=lossless') .addFields( { name: 'Phone Number', value: '703-712-6049'}, { name: 'Discord', value: 'DEFENESTRAT10N#2997'}, { name: 'Discord Alt', value: 'built different#9550'}, { name: 'Email', value: 'idfk'}, ) .setTimestamp() .setFooter({ text: 'Brought to you by YTPT Bot', iconURL: 'https://cdn.discordapp.com/emojis/810653717690318918.webp?size=240&quality=lossless' });
        if(name.toLowerCase() === "aidan") {interaction.reply({ embeds: [aidanContact] }) }
        else if(name.toLowerCase() === "andy") {interaction.reply({ embeds: [andyContact] }) }
        else if(name.toLowerCase() === "ashley") {interaction.reply({ embeds: [ashleyContact] }) }
        else if(name.toLowerCase() === "felix") {interaction.reply({ embeds: [felixContact] }) }
        else if(name.toLowerCase() === "da") {interaction.reply({ embeds: [daContact] }) }
        else if(name.toLowerCase() === "nick") {interaction.reply({ embeds: [nickContact] }) }
        else if(name.toLowerCase() === "michael") {interaction.reply({ embeds: [michaelContact] }) }
        else if(name.toLowerCase() === "pob") {interaction.reply({ embeds: [pobContact] }) }
        else if(name.toLowerCase() === "sofie") {interaction.reply({ embeds: [sofieContact] }) }
        else if(name.toLowerCase() === "toby") {interaction.reply({ embeds: [tobyContact] }) }
        else { interaction.reply({ content: `This uh "${name}" is not someone I am keeping tabs on.`})}
    }
}